### ISSUE TITLE
bad result for down faces 

### ISSUE THREAD

**Issue by Edwardmark** [daixiangzi/Caffe-PCN#1]
How you get the  model file? Using the cpp version model directly or you train the model by yourself? I test the model with down faces (180 degree angle), the result is very bad.

**Comment by yoobright** [comment]
I have same issue.

**Comment by daixiangzi** [comment]
> How you get the model file? Using the cpp version model directly or you train the model by yourself? I test the model with down faces (180 degree angle), the result is very bad.
i use cpp version model directly,the same issue in python ,so i guess precision problem on the process of c++ to python.

**Comment by SS2011** [comment]
The problem is not from model.  It is caused by mistake in stage2.  please add 4 spaces from line 143 - 150. The if-else statement is not match

correct one is:
                if self.legal(x,y,img) and self.legal(x+w-1,y+w-1,img):
                    angle =0
                    **if abs(winlist[i][4])<EPS:**
                        if maxRotateindex ==0:
                            angle = 90
                        elif maxRotateindex == 1:
                            angle = 0
                        else:
                            angle = -90
                        ret.append([x,y,w,w,angle,winlist[i][5],prob[i,1]])
                    **else:**
                        if maxRotateindex==0:
                            angle=90
                        elif maxRotateindex==1:
                            angle = 180
                        else:
                            angle = -90
                        ret.append([x,h-1-(y+w-1),w,w,angle,winlist[i][5],prob[i,1]])

**Comment by daixiangzi** [comment]
> The problem is not from model. It is caused by mistake in stage2. please add 4 spaces from line 143 - 150. The if-else statement is not match
> 
> correct one is:
> if self.legal(x,y,img) and self.legal(x+w-1,y+w-1,img):
> angle =0
> **if abs(winlist[i][4])<EPS:**
> if maxRotateindex ==0:
> angle = 90
> elif maxRotateindex == 1:
> angle = 0
> else:
> angle = -90
> ret.append([x,y,w,w,angle,winlist[i][5],prob[i,1]])
> **else:**
> if maxRotateindex==0:
> angle=90
> elif maxRotateindex==1:
> angle = 180
> else:
> angle = -90
> ret.append([x,h-1-(y+w-1),w,w,angle,winlist[i][5],prob[i,1]])

thank you very much ,i will correct immediately

**Comment by daixiangzi** [comment]
solved
