### ISSUE TITLE
How to use smoothing function or Illumination on faces ? 

### ISSUE THREAD

**Issue by muhammadabdullah34907** [daixiangzi/Caffe-PCN#2]
I have seen there are function implemented inside the PCN class but never used. I want to know how to use smoothing function or Illumination on faces after detection ?

**Comment by StefanXhunga** [comment]
Yes, I need your help to know about PCN class.
Thank you an advance

**Comment by daixiangzi** [comment]
> I have seen there are function implemented inside the PCN class but never used. I want to know how to use smoothing function or Illumination on faces after detection 
sorry，the smoothing function is used on DetectTrack module,i just implemented face detection,not to implement DetectTrack ,i suggest you watch original repository
